version: "3.8"

services:
  spring-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379

    